# Generated by Django 6.0.5 on 2026-05-24 07:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingopportunity',
            name='amount_min',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Minimum award amount.', max_digits=14),
        ),
        migrations.AddField(
            model_name='fundingopportunity',
            name='decision_timeline',
            field=models.CharField(blank=True, help_text="e.g. '4 weeks after submission'", max_length=100),
        ),
        migrations.AddField(
            model_name='fundingopportunity',
            name='fit_score',
            field=models.PositiveSmallIntegerField(default=0, help_text='Your fit rating: 0 = unrated, 1 (poor fit) to 5 (perfect fit).', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='fundingopportunity',
            name='funder_website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='fundingopportunity',
            name='geographic_eligibility',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='fundingopportunity',
            name='sector',
            field=models.CharField(blank=True, help_text='Focus area or sector targeted by the funder.', max_length=120),
        ),
        migrations.AddField(
            model_name='fundingopportunity',
            name='source_of_lead',
            field=models.CharField(blank=True, help_text='How you found this opportunity.', max_length=255),
        ),
        migrations.AddField(
            model_name='fundingopportunity',
            name='tags',
            field=models.CharField(blank=True, help_text='Comma-separated tags, e.g. agritech, women-led', max_length=300),
        ),
        migrations.AddField(
            model_name='startupdocument',
            name='parent_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versions', to='workspace.startupdocument'),
        ),
        migrations.AlterField(
            model_name='fundingopportunity',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Target / maximum award amount.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='fundingopportunity',
            name='opportunity_type',
            field=models.CharField(choices=[('grant', 'Grant'), ('loan', 'Loan'), ('debt', 'Debt Financing'), ('equity', 'Equity'), ('accelerator', 'Accelerator'), ('competition', 'Competition'), ('fellowship', 'Fellowship'), ('csr', 'CSR'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='fundingopportunity',
            name='probability',
            field=models.PositiveSmallIntegerField(default=0, help_text='Win probability from 0 to 100 percent.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='fundingopportunity',
            name='status',
            field=models.CharField(choices=[('researching', 'Researching'), ('qualifying', 'Qualifying'), ('in_progress', 'Application In Progress'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('won', 'Won'), ('lost', 'Lost'), ('withdrawn', 'Withdrawn')], default='researching', max_length=30),
        ),
        migrations.CreateModel(
            name='OpportunityStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='workspace.fundingopportunity')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_before', models.PositiveSmallIntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to='workspace.fundingopportunity')),
            ],
            options={
                'ordering': ['-sent_at'],
                'unique_together': {('opportunity', 'days_before')},
            },
        ),
    ]
