# Generated by Django 6.0.5 on 2026-05-24 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0002_fundingopportunity_amount_min_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fundingopportunity',
            name='outcome_notes',
            field=models.TextField(blank=True, help_text='Any extra context about the outcome.'),
        ),
        migrations.AddField(
            model_name='fundingopportunity',
            name='outcome_reason',
            field=models.CharField(blank=True, choices=[('strong_fit', "Strong fit with funder's focus"), ('good_network', 'Strong relationship / network'), ('polished_application', 'Polished, compelling application'), ('competitive_amount', 'Competitive funding amount requested'), ('fast_response', 'Fast and responsive communication'), ('no_fit', "No fit with funder's focus area"), ('late_submission', 'Late or incomplete submission'), ('gave_to_competitor', 'Funder awarded to a competitor'), ('no_feedback', 'No feedback received'), ('budget_cut', 'Funder budget cut or programme closed'), ('strong_competition', 'Too much competition'), ('weak_application', 'Weak or underprepared application'), ('withdrawn_by_us', 'We withdrew voluntarily'), ('other', 'Other')], help_text='Required when marking Won, Lost, or Withdrawn.', max_length=40),
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('last_interaction_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='workspace.fundingopportunity')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='workspace.startup')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InteractionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('meeting', 'Meeting'), ('call', 'Call'), ('email', 'Email'), ('other', 'Other')], default='email', max_length=20)),
                ('date', models.DateField()),
                ('summary', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='workspace.contact')),
                ('logged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
