# Generated by Django 6.0.5 on 2026-05-24 07:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_fundingopportunity_outcome_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedGrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, help_text="Funder's grant reference / contract number.", max_length=120)),
                ('funder_name', models.CharField(max_length=255)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('contract_document', models.FileField(blank=True, upload_to='grant_contracts/')),
                ('project_tag', models.CharField(blank=True, help_text='Which project/programme this grant funds.', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_grants', to=settings.AUTH_USER_MODEL)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_grants', to='workspace.fundingopportunity')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_grants', to='workspace.startup')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Disbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Tranche 1', 'Initial Payment'", max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('expected_date', models.DateField()),
                ('actual_receipt_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('delayed', 'Delayed')], default='pending', max_length=20)),
                ('bank_account', models.CharField(blank=True, max_length=255)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=6, help_text='Exchange rate to base currency, if different.', max_digits=12, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disbursements', to='workspace.managedgrant')),
            ],
            options={
                'ordering': ['expected_date'],
            },
        ),
        migrations.CreateModel(
            name='CashAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_issued', models.DateField()),
                ('person', models.CharField(max_length=255)),
                ('purpose', models.TextField()),
                ('amount_given', models.DecimalField(decimal_places=2, max_digits=14)),
                ('receipts_submitted', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('cash_returned', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_advances', to='workspace.managedgrant')),
            ],
            options={
                'ordering': ['-date_issued'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('deliverables', models.TextField(blank=True)),
                ('verification_method', models.CharField(blank=True, max_length=255)),
                ('start_month', models.DateField(help_text='First day of the starting month.')),
                ('end_month', models.DateField(help_text='Last day of the ending month.')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('approved', 'Approved')], default='not_started', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='workspace.managedgrant')),
            ],
            options={
                'ordering': ['order', 'start_month'],
            },
        ),
        migrations.CreateModel(
            name='GrantBudgetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('allocated_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_categories', to='workspace.managedgrant')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_categories', to='workspace.milestone')),
            ],
            options={
                'verbose_name_plural': 'Grant budget categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('receipt_number', models.CharField(blank=True, max_length=120)),
                ('receipt_file', models.FileField(blank=True, upload_to='expense_receipts/')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mobile_money', 'Mobile Money'), ('card', 'Card'), ('other', 'Other')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_approved', to=settings.AUTH_USER_MODEL)),
                ('paid_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses_paid', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='workspace.grantbudgetcategory')),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='workspace.managedgrant')),
                ('milestone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expenses', to='workspace.milestone')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='milestone_evidence/')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('milestone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='workspace.milestone')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
