# Generated by Django 6.0.5 on 2026-05-24 08:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_managedgrant_disbursement_cashadvance_milestone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='after_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='before_state',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='startupmember',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('startup_admin', 'Startup Admin / Founder'), ('team_member', 'Team Member'), ('field_staff', 'Field Staff'), ('auditor', 'Auditor / Read-only'), ('viewer', 'Viewer / Advisor')], default='team_member', max_length=30),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True)),
                ('level', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('danger', 'Danger')], default='info', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='workspace.startup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(help_text='ISO 4217 code, e.g. USD, EUR, KES.', max_length=10)),
                ('rate_to_tzs', models.DecimalField(decimal_places=4, help_text='How many TZS does 1 unit of this currency equal.', max_digits=14)),
                ('rate_date', models.DateField()),
                ('source', models.CharField(choices=[('bot', 'Bank of Tanzania (BoT)'), ('manual', 'Manual Entry'), ('cbk', 'Central Bank of Kenya'), ('other', 'Other')], default='bot', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rate_date', 'currency_code'],
                'unique_together': {('currency_code', 'rate_date')},
            },
        ),
    ]
