# Generated by Django 6.0.5 on 2026-05-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0005_activitylog_after_state_activitylog_before_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundingopportunity',
            name='status',
            field=models.CharField(choices=[('researching', 'Researching'), ('qualifying', 'Qualifying'), ('in_progress', 'Application In Progress'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('selected', 'Selected'), ('won', 'Won'), ('lost', 'Lost'), ('withdrawn', 'Withdrawn')], default='researching', max_length=30),
        ),
    ]
