# Generated by Django 6.0.5 on 2026-05-24 11:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0006_alter_fundingopportunity_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostedOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('funder_name', models.CharField(max_length=255)),
                ('opportunity_type', models.CharField(choices=[('grant', 'Grant'), ('loan', 'Loan'), ('equity', 'Equity Investment'), ('accelerator', 'Accelerator / Incubator'), ('competition', 'Competition / Prize'), ('fellowship', 'Fellowship'), ('debt', 'Debt Financing'), ('other', 'Other')], default='grant', max_length=30)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('coming_soon', 'Coming Soon')], default='open', max_length=20)),
                ('short_description', models.TextField(blank=True)),
                ('eligibility', models.TextField(blank=True)),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('application_link', models.URLField(blank=True)),
                ('geographic_focus', models.CharField(blank=True, max_length=255)),
                ('sector_focus', models.CharField(blank=True, max_length=255)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
