# Generated by Django 6.0.5 on 2026-05-24 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0007_postedopportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='plan',
            field=models.CharField(choices=[('solo', 'Solo — $5/mo'), ('team', 'Team — $29/mo')], default='solo', max_length=10),
        ),
        migrations.AddField(
            model_name='startup',
            name='plan_expires_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
