# Generated by Django 6.0.5 on 2026-06-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_agentrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='postedopportunity',
            name='poster_image',
            field=models.ImageField(blank=True, null=True, upload_to='opportunity_posters/'),
        ),
    ]
