from django.urls import path

from . import views


urlpatterns = [
    path("", views.home_redirect, name="home"),
    path("signup/", views.signup_view, name="signup"),
    path("onboarding/", views.onboarding_view, name="onboarding"),
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path("startup/profile/", views.startup_profile_view, name="startup_profile"),
    path("opportunities/", views.opportunity_list_view, name="opportunity_list"),
    path("opportunities/kanban/", views.kanban_view, name="kanban"),
    path("opportunities/calendar/", views.calendar_view, name="calendar"),
    path("opportunities/add/", views.opportunity_create_view, name="opportunity_add"),
    path("opportunities/<int:pk>/", views.opportunity_detail_view, name="opportunity_detail"),
    path("opportunities/<int:pk>/edit/", views.opportunity_update_view, name="opportunity_edit"),
    path("opportunities/<int:pk>/stage/", views.opportunity_stage_update, name="opportunity_stage_update"),
    path("documents/", views.document_list_view, name="document_list"),
    path("documents/add/", views.document_create_view, name="document_add"),
    path("documents/<int:pk>/edit/", views.document_update_view, name="document_edit"),
    path("documents/<int:pk>/version/", views.document_version_view, name="document_version"),
    path("budgets/", views.budget_list_view, name="budget_list"),
    path("budgets/add/", views.budget_create_view, name="budget_add"),
    path("budgets/<int:pk>/", views.budget_detail_view, name="budget_detail"),
    path("tasks/", views.task_list_view, name="task_list"),
    path("tasks/add/", views.task_create_view, name="task_add"),
    path("tasks/<int:pk>/edit/", views.task_update_view, name="task_edit"),
    path("team/", views.team_list_view, name="team_list"),
    path("team/add/", views.team_add_view, name="team_add"),
    path("reports/", views.reports_view, name="reports"),
    path("contacts/", views.contact_list_view, name="contact_list"),
    path("contacts/add/", views.contact_create_view, name="contact_add"),
    path("contacts/<int:pk>/", views.contact_detail_view, name="contact_detail"),
    path("contacts/<int:pk>/edit/", views.contact_update_view, name="contact_edit"),
    path("contacts/<int:contact_pk>/interaction/add/", views.interaction_create_view, name="interaction_add"),
    path("grants/", views.grant_list_view, name="grant_list"),
    path("grants/add/", views.grant_create_view, name="grant_add"),
    path("grants/<int:pk>/", views.grant_detail_view, name="grant_detail"),
    path("grants/<int:pk>/edit/", views.grant_update_view, name="grant_edit"),
    path("grants/<int:pk>/report/", views.grant_report_view, name="grant_report"),
    path("grants/<int:pk>/export/", views.grant_export_csv_view, name="grant_export"),
    path("grants/<int:grant_pk>/disbursements/add/", views.disbursement_add_view, name="disbursement_add"),
    path("disbursements/<int:pk>/edit/", views.disbursement_update_view, name="disbursement_edit"),
    path("grants/<int:grant_pk>/milestones/add/", views.milestone_add_view, name="milestone_add"),
    path("milestones/<int:pk>/status/", views.milestone_status_update_view, name="milestone_status"),
    path("milestones/<int:milestone_pk>/evidence/add/", views.milestone_evidence_add_view, name="milestone_evidence_add"),
    path("grants/<int:grant_pk>/budget/add/", views.budget_category_add_view, name="budget_category_add"),
    path("grants/<int:grant_pk>/expenses/add/", views.expense_add_view, name="expense_add"),
    path("grants/<int:grant_pk>/advances/add/", views.cash_advance_add_view, name="cash_advance_add"),
    path("advances/<int:pk>/reconcile/", views.cash_advance_reconcile_view, name="cash_advance_reconcile"),
    path("audit/", views.audit_log_view, name="audit_log"),
    path("notifications/", views.notification_list_view, name="notifications"),
    path("notifications/mark-read/", views.notification_mark_read_view, name="notifications_mark_all_read"),
    path("notifications/<int:pk>/read/", views.notification_mark_read_view, name="notification_read"),
    path("quick-expense/", views.quick_expense_view, name="quick_expense"),
    path("exchange-rates/", views.exchange_rate_list_view, name="exchange_rates"),
    path("board/", views.posted_opportunity_list, name="posted_opportunity_list"),
    path("board/post/", views.posted_opportunity_create, name="posted_opportunity_create"),
    path("board/<int:pk>/", views.posted_opportunity_detail, name="posted_opportunity_detail"),
    path("board/<int:pk>/add-to-pipeline/", views.posted_opportunity_add_to_pipeline, name="posted_opportunity_add_to_pipeline"),
    path("board/<int:pk>/edit/", views.posted_opportunity_edit, name="posted_opportunity_edit"),
    path("pricing/", views.pricing_view, name="pricing"),
    path("board/manage/", views.posted_opportunity_manage, name="posted_opportunity_manage"),
    path("board/<int:pk>/delete/", views.posted_opportunity_delete, name="posted_opportunity_delete"),
    # Superadmin Ops Dashboard
    path("ops/", views.ops_dashboard, name="ops_dashboard"),
    path("ops/run-agent/", views.ops_run_agent, name="ops_run_agent"),
    path("ops/opportunities/<int:pk>/toggle-status/", views.ops_opportunity_toggle_status, name="ops_opportunity_toggle_status"),
]
